# 服务端口
server:
  port: 8003
  # 服务名
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #这个是注册中心的地址
  #阿里云 vod
  #不同的服务器，地址不同
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
aliyun:
  vod:
   file:
    keyid: your accessKeyId
    keysecret: your accessKeySecret

